------------------------------------------------------------------------------
--  This file is a part of the GRLIB VHDL IP LIBRARY
--  Copyright (C) 2017, Cobham Gaisler AB - all rights reserved.
--
-- ANY USE OR REDISTRIBUTION IN PART OR IN WHOLE MUST BE HANDLED IN 
-- ACCORDANCE WITH THE GAISLER LICENSE AGREEMENT AND MUST BE APPROVED 
-- IN ADVANCE IN WRITING. 
-----------------------------------------------------------------------------   
-- Entity:      igloo2_serdes
-- File:        serdes_igloo2.vhd
-- Author:      Pascal Trotta
-- Description: Microsemi IGLOO2 serdes wrapper (configured in 10-bit EPCS mode for SGMII on Lane 3) 
------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
-- pragma translate_off
library smartfusion2;
use smartfusion2.all;
-- pragma translate_on
library techmap;
use techmap.gencomp.all;
library grlib;
use grlib.amba.all;
library work;
use work.all;

entity igloo2_serdes is
  generic(
    transtech : integer := TT_M010);
  port(
    apb_in : in apb_in_serdes;
    apb_out : out apb_out_serdes;
    insig : in sigin_serdes_type;
    outsig : out sigout_serdes_type;
    padin : in pad_in_serdes;
    padout : out pad_out_serdes);
end igloo2_serdes;

architecture igloo2_serdes_rtl of igloo2_serdes is

  component igl_serdes_epcs  -- generated by Smart Design in Libero SoC (in "work" library)
    port(
    APB_S_PADDR          : in  std_logic_vector(transtech downto 2);
    APB_S_PCLK           : in  std_logic;
    APB_S_PENABLE        : in  std_logic;
    APB_S_PRESET_N       : in  std_logic;
    APB_S_PSEL           : in  std_logic;
    APB_S_PWDATA         : in  std_logic_vector(31 downto 0);
    APB_S_PWRITE         : in  std_logic;
    EPCS_3_RESET_N       : in  std_logic;
    EPCS_3_TX_DATA       : in  std_logic_vector(19 downto 0);
    REFCLK1_N            : in  std_logic;
    REFCLK1_P            : in  std_logic;
    RXD0_N               : in  std_logic;
    RXD0_P               : in  std_logic;
    RXD1_N               : in  std_logic;
    RXD1_P               : in  std_logic;
    RXD2_N               : in  std_logic;
    RXD2_P               : in  std_logic;
    RXD3_N               : in  std_logic;
    RXD3_P               : in  std_logic;
    APB_S_PRDATA         : out std_logic_vector(31 downto 0);
    APB_S_PREADY         : out std_logic;
    APB_S_PSLVERR        : out std_logic;
    EPCS_3_READY         : out std_logic;
    EPCS_3_RX_CLK        : out std_logic;
    EPCS_3_RX_DATA       : out std_logic_vector(19 downto 0);
    EPCS_3_RX_IDLE       : out std_logic;
    EPCS_3_RX_RESET_N    : out std_logic;
    EPCS_3_RX_VAL        : out std_logic;
    EPCS_3_TX_CLK        : out std_logic;
    EPCS_3_TX_CLK_STABLE : out std_logic;
    EPCS_3_TX_RESET_N    : out std_logic;
    REFCLK1_OUT          : out std_logic;
    TXD0_N               : out std_logic;
    TXD0_P               : out std_logic;
    TXD1_N               : out std_logic;
    TXD1_P               : out std_logic;
    TXD2_N               : out std_logic;
    TXD2_P               : out std_logic;
    TXD3_N               : out std_logic;
    TXD3_P               : out std_logic);
  end component;

  component techbuf is
    generic(
      buftype  :  integer range 0 to 6 := 0;
      tech     :  integer range 0 to NTECH := inferred);
    port(
      i        :  in  std_ulogic;
      o        :  out std_ulogic
    );
  end component;

  signal tx_clk_serdes, rx_clk_serdes, tx_clk_serdes_buf, rx_clk_serdes_buf, tx_rstn_serdes, rx_rstn_serdes : std_logic;
  signal paddr : std_logic_vector(14 downto 2);

  constant delay : integer := 4;

  signal rx_val_del : std_logic_vector(delay downto 0);
  signal rx_val_serdes : std_logic_vector(1 downto 0);
  type rx_delay_type is array (0 to delay) of std_logic_vector(9 downto 0);
  signal rx_data_del : rx_delay_type;
  type rxtx_datadelay_type is array (0 to 1) of std_logic_vector(9 downto 0);
  signal tx_data_serdes, rx_data_serdes : rxtx_datadelay_type;

  signal tx_data, rx_data : std_logic_vector(19 downto 0);
  signal rx_val : std_logic;

begin
  
  -- Clocking scheme and interface as suggested in IGLOO2 High Speed Serial Interfaces User Guide and in IGLOO2 SERDES EPCS Demo    
  
  -- Regional buffers on rx and tx clocks generated by SERDES macro
  buf0: techbuf generic map(tech => igloo2, buftype => 1)
    port map (tx_clk_serdes, tx_clk_serdes_buf);

  buf1: techbuf generic map(tech => igloo2, buftype => 1)
    port map (rx_clk_serdes, rx_clk_serdes_buf);
  -----------------------------------------------------------------

  -- Register chain on data to be transmitted
  txregs0: process(tx_clk_serdes_buf, tx_rstn_serdes)
  begin
    if tx_rstn_serdes = '0' then
      tx_data_serdes(0) <= (others =>'0');
    elsif rising_edge(tx_clk_serdes_buf) then
      tx_data_serdes(0) <= insig.tx_data;
    end if;
  end process;

  txregs1: process(tx_clk_serdes, tx_rstn_serdes)
  begin
    if tx_rstn_serdes = '0' then
      tx_data_serdes(1) <= (others =>'0');
    elsif rising_edge(tx_clk_serdes) then
      for i in 0 to 9 loop -- Swap serdes input data
        tx_data_serdes(1)(9-i) <= tx_data_serdes(0)(i);
      end loop;
    end if;
  end process;
  --------------------------------------------

  -- only 10 least signficant bits are relevant for sgmii mode
  tx_data(19 downto 10) <= "0000000000";
  tx_data(9 downto 0) <= tx_data_serdes(1);
  --------------------------------------------------------------------------------------

  -- Swap serdes output data (only 10 most significant bits are relevant for sgmii mode)
  swap_rx_gen: for i in 19 downto 10 generate
    rx_data_del(0)(19-i) <= rx_data(i);
  end generate;
  --------------------------------------------------------------------------------------

  -- Delay on serdes rx data and data valid signals
  rx_val_del(0) <= rx_val;
  delay_gen0: for i in 0 to delay-1 generate
    delay_gen1: for j in 0 to 9 generate
      buf_inst: techbuf generic map(tech => igloo2, buftype => 5)
        port map (rx_data_del(i)(j), rx_data_del(i+1)(j));
    end generate;
    rx_val_del(i+1) <= rx_val_del(i);
  end generate;
  --------------------------------------------------

  -- Register chain on received data and data valid signal
  rxregs: process(rx_clk_serdes_buf, rx_rstn_serdes)
  begin
    if rx_rstn_serdes = '0' then
      rx_data_serdes(0) <= (others =>'0');
      rx_data_serdes(1) <= (others =>'0');
      rx_val_serdes(0) <= '0';
      rx_val_serdes(1) <= '0';
    elsif falling_edge(rx_clk_serdes_buf) then
      rx_data_serdes(0) <= rx_data_del(delay);
      rx_val_serdes(0) <= rx_val_del(delay);
    elsif rising_edge(rx_clk_serdes_buf) then
      rx_data_serdes(1) <= rx_data_serdes(0);
      rx_val_serdes(1) <=  rx_val_serdes(0);
    end if;
  end process;
  --------------------------------------------

  -- Output signals assignment
  outsig.tx_clk <= tx_clk_serdes_buf;
  outsig.rx_clk <= rx_clk_serdes_buf;
  outsig.rx_rstn <= rx_rstn_serdes;
  outsig.tx_rstn <= tx_rstn_serdes;
  outsig.rx_val <= rx_val_serdes(1);
  outsig.rx_data <= rx_data_serdes(1);

  paddr <= '0'&apb_in.paddr(13 downto 2);
   
  -- SERDES macro instance
  s0: igl_serdes_epcs
    port map(paddr(transtech downto 2), apb_in.pclk, apb_in.penable, apb_in.prstn, apb_in.psel, apb_in.pwdata, apb_in.pwrite,
       insig.rstn, tx_data, padin.refclkn, padin.refclkp, padin.rx0n, padin.rx0p, padin.rx1n,
       padin.rx1p, padin.rx2n, padin.rx2p, padin.rx3n, padin.rx3p, apb_out.prdata, apb_out.pready, apb_out.pslverr,
       outsig.ready, rx_clk_serdes, rx_data, outsig.rx_idle, rx_rstn_serdes, rx_val, tx_clk_serdes,
       outsig.tx_clk_lock, tx_rstn_serdes, outsig.refclk, padout.tx0n, padout.tx0p, padout.tx1n, padout.tx1p,
       padout.tx2n, padout.tx2p, padout.tx3n, padout.tx3p);

end;

