#ifndef CONFIG_GRADCDAC_ENABLE
#define CONFIG_GRADCDAC_ENABLE 0
#endif
#ifndef CONFIG_GRADCDAC_DWIDTH
#define CONFIG_GRADCDAC_DWIDTH 16
#endif
#ifndef CONFIG_GRADCDAC_ABITS
#define CONFIG_GRADCDAC_ABITS 4
#endif
#ifndef CONFIG_GRADCDAC_IRQ
#define CONFIG_GRADCDAC_IRQ 0
#endif
