#ifndef CONFIG_GRFIFO_ENABLE
#define CONFIG_GRFIFO_ENABLE 0
#endif
#ifndef CONFIG_GRFIFO_WIDTH
#define CONFIG_GRFIFO_WIDTH 16
#endif
#ifndef CONFIG_GRFIFO_IRQ
#define CONFIG_GRFIFO_IRQ 0
#endif
#ifndef CONFIG_GRFIFO_ABITS
#define CONFIG_GRFIFO_ABITS 16
#endif
#ifndef CONFIG_GRFIFO_SINGLE
#define CONFIG_GRFIFO_SINGLE 0
#endif


